source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'will_paginate', '~> 3.0.pre2'
gem 'gravatar_image_tag'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development do
  #include for access to RSpec-specific generators
  # execute the follow command to use RSpec in place of Test::Unit
  # $> rails generate rspec:install
  gem 'rspec-rails', '~>2.0.0.beta.20'
  gem 'annotate-models'
  gem 'faker'
end

group :test do
  gem 'rspec', '~>2.0.0.beta.20'
  gem 'autotest', '~>4.3.2'
  gem 'autotest-rails', '~>4.1.0'
  gem 'spork'
  gem 'webrat'
  gem 'factory_girl_rails'
end

#execute the following to use jQuery
#rake rails:template LOCATION=http://github.com/lleger/Rails-3-jQuery/raw/master/jquery.rb
